apiVersion: v2
name: jenkins-chart
description: A Helm chart to deploy Jenkins with custom config
type: application
version: 0.1.0
appVersion: "2.x"
dependencies:
  - name: jenkins
    version: 5.8.52
    repository: https://charts.jenkins.io
    condition: jenkins.enabled