name: Terraform Deployment

on:
  push:
    branches:
      - task_1
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Check formatting
        run: terraform fmt -check -diff -recursive

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_repo_fullname: ${{ secrets.REPO_FULLNAME }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_role_name: ${{ secrets.ROLE_NAME }}

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_repo_fullname: ${{ secrets.REPO_FULLNAME }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_role_name: ${{ secrets.ROLE_NAME }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform 
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_repo_fullname: ${{ secrets.REPO_FULLNAME }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_role_name: ${{ secrets.ROLE_NAME }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_repo_fullname: ${{ secrets.REPO_FULLNAME }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_role_name: ${{ secrets.ROLE_NAME }}
